CREATE TABLE users (
                       id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email           VARCHAR2(255) NOT NULL,
                       password        VARCHAR2(255) NOT NULL,
                       created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                       updated_at      TIMESTAMP,
                       deleted_at      TIMESTAMP
);

CREATE SEQUENCE SEQ_USER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
